name: touch
description: Touch Other Lives With Your Steps

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  flutter_svg: ^0.19.1
  url_launcher: ^5.4.2
  provider: ^4.3.1 # for State management
  simple_animations: ^1.3.3
  animated_text_kit: ^1.1.0
  shared_preferences: ^0.5.6
  convex_bottom_bar: ^2.1.1
  google_fonts: ^1.1.0
  expansion_tile_card: ^1.1.0
  percent_indicator: ^2.1.9+1
  pedometer: ^2.1.0
  step_progress_indicator: ^0.2.4+7
  scrollable_bottom_sheet: ^0.2.1
  flutter_staggered_grid_view: ^0.3.0

  # Settings
  persist_theme: ^1.6.0
  http: ^0.12.0+1    

  # Floating Action Button
  unicorndial: ^1.1.5

  # Google Maps
  geolocator: ^5.1.5
  permission_handler: ^4.0.0
  location: ^2.3.5
  google_maps_flutter: ^0.5.21+10
  fluttertoast: ^3.1.3
  
  # Multiple Language
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.8.0

  flutter_native_splash: ^0.1.9

flutter_native_splash:
  color: "E11E3C"
  android_disable_fullscreen: true
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icons/
    - assets/images/
    - assets/images/splash/
    - assets/images/welcome/
    - assets/images/charity/     
    - assets/images/badges/
    - assets/langs/
    - assets/map/map_style.json
    - assets/images/map/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Muli
      fonts:
        - asset: assets/fonts/muli/Muli.ttf
        - asset: assets/fonts/muli/Muli-Bold.ttf
          weight: 700
        - asset: assets/fonts/muli/Muli-Light.ttf
          weight: 300
    - family: Nunito
      fonts:
        - asset: assets/fonts/nunito/Nunito-Black.ttf
          weight: 800
        - asset: assets/fonts/nunito/Nunito-Bold.ttf
          weight: 900
        - asset: assets/fonts/nunito/Nunito-Light.ttf
          weight: 300
        - asset: assets/fonts/nunito/Nunito-Medium.ttf
          weight: 700    
    - family: Nexa
      fonts:
        - asset: assets/fonts/Nexa-Bold.otf
    - family: NexaLight
      fonts:
        - asset: assets/fonts/Nexa-Light.otf  
    - family: BalooBhaina
      fonts:
        - asset: assets/fonts/BalooBhaina2-Regular.otf
    
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
