import 'package:flutter/material.dart';

class Badge {
  final String image, title, description;
  final int level, size, id;
  final Color color;
  Badge({
    this.id,
    this.image,
    this.title,
    this.level,
    this.description,
    this.size,
    this.color,
  });
}

List<Badge> badges = [
 Badge(
      id: 1,
      title: "",
      level: 1,
      size: 10,
      description: dummyText,
      image: "assets/images/badges/badge_003.jpg",
      color: Color(0xFF3D82AE)),
  Badge(
      id: 2,
      title: "",
      level: 1,
      size: 10,
      description: dummyText,
      image: "assets/images/badges/badge_004.jpg",
      color: Color(0xFFD3A984)),
  Badge(
      id: 3,
      title: "",
      level: 1,
      size: 10,
      description: dummyText,
      image: "assets/images/badges/badge_005.jpg",
      color: Color(0xFF989493)),
  Badge(
      id: 4,
      title: "",
      level: 1,
      size: 10,
      description: dummyText,
      image: "assets/images/badges/badge_006.jpg",
      color: Color(0xFFE6B398)),
  Badge(
      id: 5,
      title: "",
      level: 1,
      size: 10,
      description: dummyText,
      image: "assets/images/badges/badge_007.jpg",
      color: Color(0xFFFB7883)),
  Badge(
    id: 6,
    title: "",
    level: 1,
    size: 10,
    description: dummyText,
      image: "assets/images/badges/badge_008.jpg",
    color: Color(0xFFAEAEAE),
  ),
  Badge(
      id: 7,
      title: "",
      level: 1,
      size: 10,
      description: dummyText,
      image: "assets/images/badges/badge_009.jpg",
      color: Color(0xFFFB7883)),
  Badge(
    id: 8,
    title: "",
    level: 1,
    size: 10,
    description: dummyText,
      image: "assets/images/badges/badge_010.jpg",
    color: Color(0xFFAEAEAE),
  ),
  Badge(
    id: 9,
    title: "",
    level: 1,
    size: 10,
    description: dummyText,
      image: "assets/images/badges/image_part_001.jpg",
    color: Color(0xFFAEAEAE),
  ),
  Badge(
    id: 10,
    title: "",
    level: 1,
    size: 10,
    description: dummyText,
      image: "assets/images/badges/image_part_002.jpg",
    color: Color(0xFFAEAEAE),
  ),
  Badge(
    id: 11,
    title: "",
    level: 1,
    size: 10,
    description: dummyText,
      image: "assets/images/badges/image_part_003.jpg",
    color: Color(0xFFAEAEAE),
  ),
  Badge(
    id: 12,
    title: "",
    level: 1,
    size: 10,
    description: dummyText,
      image: "assets/images/badges/image_part_004.jpg",
    color: Color(0xFFAEAEAE),
  ),
  Badge(
    id: 13,
    title: "",
    level: 1,
    size: 10,
    description: dummyText,
      image: "assets/images/badges/image_part_005.jpg",
    color: Color(0xFFAEAEAE),
  ),
  Badge(
    id: 14,
    title: "",
    level: 1,
    size: 10,
    description: dummyText,
      image: "assets/images/badges/image_part_006.jpg",
    color: Color(0xFFAEAEAE),
  ),
  Badge(
    id: 15,
    title: "",
    level: 1,
    size: 10,
    description: dummyText,
      image: "assets/images/badges/image_part_007.jpg",
    color: Color(0xFFAEAEAE),
  ),
  Badge(
    id: 16,
    title: "",
    level: 1,
    size: 10,
    description: dummyText,
      image: "assets/images/badges/image_part_008.jpg",
    color: Color(0xFFAEAEAE),
  ),
  Badge(
    id: 17,
    title: "",
    level: 1,
    size: 10,
    description: dummyText,
      image: "assets/images/badges/image_part_009.jpg",
    color: Color(0xFFAEAEAE),
  ),
  Badge(
    id: 18,
    title: "",
    level: 1,
    size: 10,
    description: dummyText,
      image: "assets/images/badges/image_part_010.jpg",
    color: Color(0xFFAEAEAE),
  ),
  Badge(
    id: 19,
    title: "",
    level: 1,
    size: 10,
    description: dummyText,
      image: "assets/images/badges/image_part_011.jpg",
    color: Color(0xFFAEAEAE),
  ),
  Badge(
    id: 20,
    title: "",
    level: 1,
    size: 10,
    description: dummyText,
      image: "assets/images/badges/image_part_012.jpg",
    color: Color(0xFFAEAEAE),
  ),
];

String dummyText =
    "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since. When an unknown printer took a galley.";
